version: '3.8'
services:

  lanchonete-pedido-app:
    build: .
    container_name: lanchonete-app-pedido
    image: gtbarbosa/fiap-tech-challenge-lanchonete-api-pedido:latest
    ports:
      - 8181:8181
    networks:
      - lanchonete-network
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8
    container_name: mysql-lanchonete-pedido-db
    ports:
      - 3307:3306
    networks:
      - lanchonete-network
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: pedido
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppass"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  lanchonete-network:
