apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-lanchonete-app-pedido
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-lanchonete-app-pedido
  template:
    metadata:
      labels:
        app: pod-lanchonete-app-pedido
    spec:
      containers:
        - name: container-lanchonete-app-pedido
          image: gtbarbosa/fiap-tech-challenge-lanchonete-api-pedido
          env:
            - name: PRODUTO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap-pedido
                  key: PRODUTO_ENDPOINT
            - name: CLIENTE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap-pedido
                  key: CLIENTE_ENDPOINT
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap-pedido
                  key: APP_NAME
            - name: DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: app-configmap-pedido
                  key: DDL_AUTO
            - name: SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: app-configmap-pedido
                  key: SHOW_SQL
            - name: URL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-configmap-pedido
                  key: URL_DATABASE
            - name: USER_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-configmap-pedido
                  key: USER_DATABASE
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap-pedido
                  key: APP_PORT
            - name: PASSWORD_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-pedido
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "700m"
              memory: "768Mi"