apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap-pedido
data:
  APP_NAME: lanchonete
  DDL_AUTO: create-drop
  SHOW_SQL: "true"
  URL_DATABASE: jdbc:mysql://svc-mysql-db-pedido:3306/lanchonete-pedido
  USER_DATABASE: user
  APP_PORT: "80"
  MYSQL_DATABASE: lanchonete-pedido
  MYSQL_USER: user
  PRODUTO_ENDPOINT: http://ac8467dabee42434fad6ceffc7661071-219717076.us-east-1.elb.amazonaws.com/produto
  CLIENTE_ENDPOINT: http://af87f4bae44e346b7a72044eda3133ef-1356554212.us-east-1.elb.amazonaws.com/cliente